apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloname
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: helloname
  template:
    metadata:
      labels:
        app: helloname
    spec:
      containers:
        - image: mxwest.jfrog.io/argocd-demo-docker-local/helloname:d24a21f
          name: helloname
          ports:
            - containerPort: 80
